spring:
  application:
    name: api-service

server:
  port: 8080

eureka:
  instance:
    hostname: localhost
    port: 9050
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    fetch-registry: true

logging:
  level.com.github.bilak: DEBUG